package com.example.dongiusseppiapp.domain.model

enum class MenuModel {
    AMERICANA,
    MEDIA_AMERICANA,
    PORCION_AMERICANA,
    HAWAIANA,
    MEDIA_HAWAIANA,
    PORCION_HAWAIANA,
    OLIVO,
    MEDIA_OLIVO,
    PORCION_OLIVO,

    ARROZ_CON_LECHE,
    BROWNIES,
    EMPANADAS,
    ROLLOS_CANELA,
    YOGGIS,

    HELADO,
    HELADO_4_BOLAS,

    SEVEN_UP_PERSONAL,
    SEVEN_UP_1LT,
    SPORADE_PERSONAL,
    COCA_COLA_PERSONAL,
    CONCORDIA_PERSONAL,
    CONCORDIA_1LT,
    FANTA_PERSONAL,
    INCA_KOLA_PERSONAL
}